name: build
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 10.x, 12.x, 14.x, 15.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run bootstrap
      - run: npm run build
      - run: npm run test
      - run: npm run e2e
      - run: npm run perf

  publish:
    name: Publish
    needs: build

    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run bootstrap
      - run: npm run build
      - run: git config --global user.name 'ima-bot'
      - run: git config --global user.email 'ima-bot@ima-tech.ca'
      - run: npm run bump-patch
      - run: npm run publish-ci